name: Build project and upload to AWS S3

on:
  push:
    branches:
      - main

permissions:
  contents: read

# env:
#   AWS_S3_BUCKET_NAME: githubaction-bucket

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Upload code
        uses: actions/upload-artifact@v4
        with:
          name: project
          path: ./project

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: install JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: project
      - name: Build project
        run: chmod +x gradlew && ./gradlew build
        working-directory: ${{ env.working-directory }}
      - name: Make zip file
        run: zip -r project-jar.zip ./build/libs/*.jar
        # shell: bash
  # upload-aws-s3:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Configure AWS S3 credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ap-northeast-2
  #     - name: Upload to AWS S3
  #       run: aws s3 cp --region ap-northeast-2 ./project.zip s3://$AWS_S3_BUCKET_NAME/