# name: 'Hello Github Actions'
# on:
#   push:
#     branches:
#       - main
# jobs:
#   echo:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Echo Hello GitHub Actions!!
#         run: echo Hello Github Actions!!
name: GitHub Actions Demo
run-name: is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Hello World!!!"
      - run: echo "ğŸ§ This job is now running on a server hosted by GitHub!"